# ACME_StandardLibrary

In [5]:
#problem1
def f1(list):
    a=min(list)
    b=max(list)
    c=sum(list)/len(list)
    return a,b,c
f1([1, 2, 3])

(1, 3, 2)

In [29]:
#problem2
#int
a=3
b=a
b=4
a==b

False

In [30]:
#str
a="apple"
b=a
b="banana"
a==b

False

In [31]:
#list
a = [1, 2, 3]
b=a
b[1]=4
a==b

True

In [32]:
#tuple
a=(1,2,3)
b=a
b[1]=4
a==b

TypeError: 'tuple' object does not support item assignment

In [34]:
#set
a={1,2,3,3,4}
b=a
b.add(2)
a==b

True

#int, str, and tuple are immutable, list and set are mutable

In [13]:
#problem3
from math import sqrt
import calculator as cl
def tri(a,b):
    c=sqrt(cl.f1(cl.f2(a,a),cl.f2(b,b)))
    return c

# AMCE_NumpyIntro

In [24]:
import numpy as np
#problem1
def f1():
    a=np.array([[3,-1,4],[1,5,-9]])
    b=np.array([[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]])
    c=np.dot(a,b)
    return c
f1()

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [25]:
#problem2
def f2():
    a=np.array([[3,1,4],[1,5,9],[-5,3,1]])
    b=-a*a*a+9*a*a-15*a
    return b
f2()

array([[   9,   -7,   20],
       [  -7,   25, -135],
       [ 425,    9,   -7]])

In [26]:
#problem3
a=np.array([[0,2,4],[1,3,5]])
b=np.array([[3,0,0],[3,3,0],[3,3,3]])
c=np.array([[-2,0,0],[0,-2,0],[0,0,-2]])
e1=np.vstack((np.zeros((3,3)),a,b))
e2=np.vstack((a.T,np.zeros((2,2)),np.zeros((3,2))))
e3=np.vstack((np.ones((3,3)),np.zeros((2,3)),c))
e=np.hstack((e1,e2,e3))
e

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  2.,  3.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  4.,  5.,  1.,  1.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

# ACME_Objective Oriented

In [27]:
class Backpack:
    '''
    Attributes:
    name (str): the name of the Backpack.
    color (str): the color of the Backpack.
    max_size (int): the maximum number of items that can fit inside.
    contents (list): the contents of the backpack.

    Methods:
    put(item): add item if number of items in class does not exceed max_size
    dump: empty content of self
    
    '''
    #problem1
    def __init__(self, name,color,max_size=5): 
        self.name = name 
        self.color = color
        self.max_size=max_size
        self.contents =[]
    #problem2
    def put(self, item):
        count=0
        for k in self.contents:
             count +=1
        if count>=self.max_size:
            print("No Room!")
        else:
            self.contents.append(item)
    #problem3
    def dump(self):
        self.contents =[]

In [ ]:
class Jetpack(Backpack):
    '''
    Attributes:
    name (str): the name of the Jetpack.
    color (str): the color of the Jetpack.
    max_size (int): the maximum number of items that can fit inside.
    contents (list): the contents of the backpack.
    fuleamount (int): amount of fuel
    
    Methods:
    fly: input an amount of fuel to be burned and decrement the fuel attribute by that amount if amount of fuel 
            to be burned is less than fuel attribute.
    dump: empty content and amount of fule
    
    '''
    #problem1
    def __init__(self, name, color, max_size=2,fuleamount=10):
        self.fuleamount = fuleamount
        Backpack.__init__(self, name, color, max_size)
    #problem2
    def fly(self, fuleburn):
        if fuleburn>self.fuleamount:
            print("Not enough fule!")
        else:
            self.fuleamount=self.fuleamount-fuleburn
    #problem3
    def dump(self):
        self.contents =[]
        self.fuleamount=0